# Generated by Django 5.1.7 on 2025-06-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
