# Generated by Django 5.1.7 on 2025-06-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_dishes_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='cat',
            new_name='category',
        ),
    ]
