# Generated by Django 5.1.7 on 2025-06-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comments',
            new_name='fcomments',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='femail',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='rating',
            new_name='frating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='submitted_at',
        ),
    ]
