# Generated by Django 5.1.7 on 2025-06-20 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_comments_feedback_fcomments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('srole', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=254)),
                ('simage', models.ImageField(upload_to='pics')),
                ('sphone', models.IntegerField(max_length=10)),
                ('shours', models.IntegerField(max_length=15)),
                ('ssalary', models.IntegerField(max_length=20)),
                ('sorders', models.IntegerField()),
                ('srating', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('slevel', models.CharField(max_length=10)),
                ('sdesc', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
