# Generated by Django 5.1.7 on 2025-06-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='shours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sphone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ssalary',
            field=models.IntegerField(),
        ),
    ]
