# Generated by Django 5.1.7 on 2025-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_staff_shours_alter_staff_sphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='femail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sdesc',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='semail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='shours',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sorders',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sphone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='srating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ssalary',
            field=models.CharField(max_length=900000),
        ),
    ]
